pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Camera2RTSP"

// RootEncoder como modulo local (tag 2.7.2)
// Clone com: git clone --branch 2.7.2 --depth 1 https://github.com/pedroSG94/RootEncoder.git C:\Users\Luan\StudioProjects\RootEncoder
includeBuild("../RootEncoder") {
    dependencySubstitution {
        substitute(module("com.github.pedroSG94.RootEncoder:library")).using(project(":library"))
    }
}

include ':app'
