pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Camera2RTSP"

// RootEncoder como modulo local
// Clone o repositorio em: C:\Users\Luan\StudioProjects\RootEncoder
// Comando: git clone --branch 2.6.7 https://github.com/pedroSG94/RootEncoder.git C:\Users\Luan\StudioProjects\RootEncoder
includeBuild("../RootEncoder") {
    dependencySubstitution {
        substitute(module("com.github.pedroSG94.RootEncoder:library")).using(project(":library"))
    }
}

include ':app'
